In [24]:
#4 plot , 2 hissy, 3 hissy
#Multi  Dimension array

#4 array hyn har array mein  2 array hyn or har 2 array mein 3 elements hyn

import numpy as np
d3 = np.asarray([
    [
        [111,112,113],
        [121,122,123]
    ],
    [
        [211,212,213],
        [221,222,223]
    ],
    [
        [311,312,313],
        [321,322,323]
    ],
    [
        [411,412,413],
        [421,422,423]
    ]
    ])

print("Array: \n",d3)
print("\n\nShape",d3.shape)
print("Size",d3.size)
print("Dimension",d3.ndim)
x=list

Array: 
 [[[111 112 113]
  [121 122 123]]

 [[211 212 213]
  [221 222 223]]

 [[311 312 313]
  [321 322 323]]

 [[411 412 413]
  [421 422 423]]]


Shape (4, 2, 3)
Size 24
Dimension 3


In [18]:

d3[:2,:1,:1]


array([[[111]],

       [[211]]])

In [19]:
d3[2,1,1]

322

In [26]:
#Vectoriztion
arr=np.array([12,-45,67,89,34,-2,-2,6,-7,8])
print(arr * 6)#scalar operation will propogate
print(arr[:3] * 6)
#in list we cannot do that
#x=list(arr)
#print(x*6)



[  72 -270  402  534  204  -12  -12   36  -42   48]
[  72 -270  402]


In [37]:
#equal array operations
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[4,11,6]])

c= a+b
print("\na+B ",c)

#broadcasting(row size should be same)
d=np.array([4,3,2])
print("\nSHAPE: ",c.shape,d.shape)

print("\n C+D: ",c+d)




a+B  [[ 8 10 12]
 [ 8 16 12]]

SHAPE:  (2, 3) (3,)

 C+D:  [[12 13 14]
 [12 19 14]]


In [44]:
#comparing arry will return boolean
#we can use boolean array for filtering data
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[4,11,6]])

boolean_e = (a==b)
c=a+b
boolean_e=(c<=10)
print(c)
print(boolean_e)

#Filtering data using boolean array
cFilter=c[boolean_e]
print(cFilter)

[[ 8 10 12]
 [ 8 16 12]]
[[ True  True False]
 [ True False False]]
[ 8 10  8]


In [46]:
#indexing and fancy indexing

#normal indexing
arr=np.array([12,-45,67,89,34,-2,-2,6,-7,8])
print(arr[4])

#fancy indexing
ind=[1,4,6]
print(arr[ind])

34
[-45  34  -2]


In [2]:
#NUMPY VS PYTHON
l=range(1000000)

In [4]:
import numpy as np


In [6]:
d=np.arange(1000000)



In [10]:
%time for i in range(1,10): r=[x*2 for x in l]

Wall time: 2 s


In [14]:
%time for i in range(1,10): r=d*2

Wall time: 72 ms


In [15]:
#Creating multidimensial array of ones
x=np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
#Creating multidimensial array of ones
y=np.ones((4,4))
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
#Creating random aray
z=np.empty((2,2))
z

array([[1.33360341e+241, 8.39037136e-311],
       [1.85505085e-229, 2.06466926e+161]])

In [19]:
#Convering list into array
lst=[1,2,3,4]
x=np.array(lst)
x

array([1, 2, 3, 4])

In [20]:
#range 1 sy ly kar 200 tk 20 steps choe k
np.arange(1,200,20)


array([  1,  21,  41,  61,  81, 101, 121, 141, 161, 181])

In [25]:
x=np.zeros((10,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
x.shape


(10, 10)

In [33]:
y=x.reshape((2,2,5,5))
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [35]:
y.dtype

dtype('float64')

In [37]:
y.ndim

4