In [25]:
import numpy as np
text="Here are some of the things you'll find in NumPy"
l=text.split(" ")
arr=np.array(text.split(" "))
prn= print
prn("testing")
print(arr)
#for a in arr:
 #   if len(a)<5:
  #      print(a)
#print(len(arr))
#lnth = np.vetorize(len)
#print(arr[lnth(arr)<5])
print(arr[(np.vectorize(len)) (arr)<5])
print()

#text1="How dare you! you can't do that"
#text2+="Do you want a break? or if you dont want to practice"
#print(text1)



testing
['Here' 'are' 'some' 'of' 'the' 'things' "you'll" 'find' 'in' 'NumPy']
['Here' 'are' 'some' 'of' 'the' 'find' 'in']



In [14]:
x=np.zeros((2,3,2,3))
print(x.ndim)
print(x.shape)
x[1,1,0,1:3]=7
x

4
(2, 3, 2, 3)


array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 7., 7.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [17]:
#Foe documentetions
#np.function_name?
np.abs(-1)

1

In [22]:
arr=np.ones(4)
arr[0:-1]=-1
arr


array([-1., -1., -1.,  1.])

In [24]:
np.abs(arr)

array([1., 1., 1., 1.])

In [25]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
np.where(arr<5,arr,arr*4)

array([ 1,  2,  3,  4, 20, 24, 28, 32, 36, 40])

In [29]:
arr.mean()

5.5

In [30]:
arr.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55], dtype=int32)

In [31]:
arr.cumprod()

array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800], dtype=int32)

In [32]:
arr.sum(
)

55

In [33]:
arr.any()

True

In [34]:
arr.all()

True

In [37]:
arr2= arr>5
arr2.sum()

5

In [41]:
# any(arr==5)
any(arr==155)

False

In [43]:
# all(arr<11)
all(arr>1)

False

In [49]:
arr=np.array([12,-45,67,89,34,-2,-2,6,-7,8])
arr

array([ 12, -45,  67,  89,  34,  -2,  -2,   6,  -7,   8])

In [50]:
np.sort(arr)

array([-45,  -7,  -2,  -2,   6,   8,  12,  34,  67,  89])

In [51]:
np.unique(arr)

array([-45,  -7,  -2,   6,   8,  12,  34,  67,  89])

In [56]:
np.random.seed(7)
print(np.random.rand(3))

[0.07630829 0.77991879 0.43840923]


In [20]:
arr=np.arange(10,100,5)
arr
                    

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [21]:
a,b,c=np.split(arr,[2,6]) #start+1,end
#OR a,b,c=arr

In [22]:
a

array([10, 15])

In [23]:
b


array([20, 25, 30, 35])

In [24]:
c

array([40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [31]:
arr=np.arange(1,11)
print(x)
x =  np.split(arr,[2,4,6,8])
print(x[0])
print(x[1])
print(x[2])
print(x[3])

[ 1  2  3  4  5  6  7  8  9 10]
[1 2]
[3 4]
[5 6]
[7 8]
